name: updateLPR
on: 
  push:
  pull_request:
  schedule:
    - cron: 30 9 19-25 * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: checkout <LPR.XML>
        uses: moonrailgun/branch-filestorage-action@v1.2.2
        with: 
            path: LPR.xml
      - name: Install Dependency
        run: |
         npm install 
      - name: Update LPR.xml
        run: node ./index.js
