name: updateLPR
on: 
  push:
  pull_request:
  schedule:
    - cron: 0 9 19-25 * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      
      - name: Install Dependency
        run: |
         npm install 
        
      - name: Working
        run: node ./index.js

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
            SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
            source-repo: git@github.com:eatomelette/lpr.git
            destination-repo: git@gitee.com:cpvhelper/lpr.git 