name: updateLPR
on: 
  push:
  pull_request:
  schedule:
    - cron: 30 9 19-25 * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: 18
          
      - name: Install Dependency
        run: npm install 
        
      - name: Update LPR.xml and generate HTML
        run: node ./index.js
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # 发布当前目录
          publish_branch: gh-pages  # 使用 gh-pages 分支
          keep_files: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update LPR data - ${{ github.run_number }}'