name: updateLPR
on: 
  push:
    branches:[ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron 0 9 19-25 * *
jobs:
  build:
    runs-on: ubuntu-latest
    step:
      - uses: actions/checkout@main

      - name: Setup Nodejs
        uses: actions/step-node@v2
        with: 
          node-version: '14'
      
      - name: Install Dependency
        run: |
         npm install 
        
      - name: Working
        run: node ./index.js

