name: updateLPR
on: 
  push:
    branches:[ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - corn 0 9 19-25 * *
jobs:
  build:
    runs-on: ubunt-latest
    step:
      - uses: actions/checkout@main

      - name: Setup Nodejs
        uses: actions/step-node@v2
        with: 
          node-version: '14'
      
      - name: Install Dependency
        run: |
         npm install 
        
      - name: Working
        run: node ./index.js

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
            SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
            source-repo: git@github.com:eatomelette/lpr.git
            destination-repo: git@gitee.com:cpvhelper/lpr.git
